---
# task for apache2 webserver
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Install apache httpd  (state=present is optional)
  apt:
    name: apache2
    state: present

- name: Create document root
  file:
    path: "/var/www/{{ http_host }}"
    state: directory
    owner: "{{ app_user }}"
    mode: '0755'

- name: "UFW - Allow HTTP on port {{ http_port }}"
  ufw:
    rule: allow
    port: "{{ http_port }}"
    proto: tcp

handlers:
- name: Reload Apache
  service:
    name: apache2
    state: reloaded

- name: Restart Apache
  service:
    name: apache2
    state: restarted